import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import { ReduxProvider } from "@/store/Provider/ReduxProvider";
import { Navbar } from "@/widgets/navbar/Navbar";
import { Footer } from "@/widgets/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SolarHelper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={inter.className}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </ReduxProvider>
    </html>
  );
}
